- index.html
- package-lock.json
- package.json
- src/polyfills.ts
> add polyfill for ie css variable support

- Dockerfile
> Dockerfile now builds using containers artifacts

- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.html
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.scss
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.spec.ts
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.ts
- src/index.html
> Added conditional rendering for non link elements

- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.ts
> Added condition for footer sticky behavior

- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.html
- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.scss
- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.ts
> Added styling for wvr-text node

- scripts/build-wvr-components.js
> Sprint4 72 bundle latest build

- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.scss
> Added rul to have height of 100% for navbar

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.html
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
- src/index.html
> Sprint5 81 conditional display bottom nav

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.html
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.html
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-list.component.html
- src/index.html
> Accessibility for wvr-header component

- .gitignore
- .wvr-ud/config.json
- README.md
> Modified ReadMe file

- .wvr-ud/config.json
- index-docs.html
- index-reports.html
- index-static.html
- karma.conf.js
- scripts/build-wvr-components-lighthouse-badges.js
- scripts/build-wvr-components-static.js
> Added weaver-component to the path

- README.md
> Modified ReadMe file path by adding weaver-components in the URL path

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.html
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.scss
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
> Added attribute page-title-url to weaver header component

- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
> Renamed dropdown selector

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
> sprint7-136: Bottom Navigation Dynamic Content

- index.html
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.scss
- src/index.html
> Added z-index for wvr drop down menu

- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
> Sprint7-119, Dropdown Flicker

- index.html
- src/index.html
> Modified both index files removing menu background

- index.html
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.spec.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.ud-examples.html
- src/index.html
> Sprint7 103 wvr button

- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.scss
Resolves #103 
Fixed info border style typo
> Fixed typo for info border style

- index.html
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.html
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.scss
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.spec.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.ud-examples.html
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.scss
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
- projects/wvr-elements/src/lib/wvr-lib.module.ts
- projects/wvr-elements/src/public-api.ts
- src/index.html
Resolves #103 - Wvr Components should provide a `wvr-button` component
Resolves #135 - CDN needs to be exposed through the firewall 
Resolves #133 - Fix Z-Index on dropdown overlaps
Resolves #136 - Restore dynamic change detection for display of bottom nav
Resolves #119 - Dropdown inside of List inside of Header flickers instead of staying open
> Sprint7 staging

- package.json
- projects/wvr-elements/package.json
> Bumped Version

- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.ts
- src/index.html
> Addressed stick-to-bottom feature in wvr footer

- index.html
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.scss
- src/index.html
Style fix for buttons in index html
> Style fixes

- projects/wvr-elements/src/lib/wvr-icon/wvr-icon.component.ts
Resolves #168 
This resolves the issue by converting replacing the subscription with a conversion to promise and executing the login in the then block.
> Avoiding hanging subscription via toPromise

- .travis.yml
- package.json
Resolves #167 Coveralls not providing the coverage notification
> Sprint9 167 coveralls

- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
Resolves TAMULib/tamu-library-components#151
> Fixed issue with screen size returning 0

- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
- src/index.html
- src/styles.scss
Conditional display of components in mobile view.
> Sprint10 157 conditional mega menu mobile view

- projects/wvr-elements/src/lib/core/component-registry.service.spec.ts
- projects/wvr-elements/src/lib/core/component-registry.service.ts
- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
> Sprint11 208 uid

- lighthouserc.json
- projects/wvr-elements/src/lib/wvr-list/wvr-list-item/wvr-list-item.component.html
- projects/wvr-elements/src/lib/wvr-list/wvr-list-item/wvr-list-item.component.ts
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.html
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.ts
- src/index.html
> Sprint11 206 aria owns

- .travis.yml
- angular.json
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts
Test PR to a test staging branch
> Sprint11 211 project coverage report

- angular.json
> Modified the angular json for code coverage

- angular.json
- projects/wvr-elements/src/lib/core/component-registry.service.ts
- projects/wvr-elements/src/lib/core/rest/rest.effects.ts
- projects/wvr-elements/src/lib/core/rest/rest.service.ts
- projects/wvr-elements/src/lib/core/template.service.ts
- projects/wvr-elements/src/lib/shared/pipes/default.pipe.spec.ts
- projects/wvr-elements/src/lib/shared/pipes/default.pipe.ts
- projects/wvr-elements/src/lib/shared/pipes/safe.pipe.spec.ts
- projects/wvr-elements/src/lib/shared/pipes/safe.pipe.ts
- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
- projects/wvr-elements/src/lib/wvr-lib.module.ts
- projects/wvr-elements/src/lib/wvr-list/wvr-list-item/wvr-list-item.component.ts
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.html
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.ts
- projects/wvr-elements/src/lib/wvr-manifest/mapping-strategies.ts
- projects/wvr-elements/src/lib/wvr-manifest/mapping-strategy.ts
- projects/wvr-elements/src/lib/wvr-manifest/wvr-manifest-entry/wvr-manifest-entry.component.ts
- projects/wvr-elements/src/lib/wvr-manifest/wvr-manifest.component.ts
- src/index.html
> Sprint12 223 map strategy

- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.html
- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.scss
- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.ts
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.html
- src/index.html
> Sprint12 234 wvre cards

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
- src/assets/weaver-w.svg
the logoSrc now points to assets/icons/custom/weaver.svg file using the assetsUrl variable
> sprint12-staging-fixes

- package.json
- projects/wvr-elements/package.json
- projects/wvr-elements/src/lib/shared/utility/bootstrap.utility.ts
- src/main.ts
Resolves #205 config.json doesn't load inside iframe.
> sprint13-205-config-json

- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
Resolves #224 - TL Mega Menu should remain open when clicked
> Sprint13-224-tl-mega-menu-remain-open

- package.json
- projects/wvr-elements/ng-package.json
- projects/wvr-elements/package.json
- projects/wvr-elements/src/lib/core/handlebars-helpers.ts
- projects/wvr-elements/src/lib/core/template.service.spec.ts
- projects/wvr-elements/src/lib/core/template.service.ts
- projects/wvr-elements/src/lib/core/wvr-animation-component.ts
- projects/wvr-elements/src/lib/core/wvr-animation.service.spec.ts
- projects/wvr-elements/src/lib/core/wvr-animation.service.ts
- projects/wvr-elements/src/lib/core/wvr-data-component.ts
- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
- projects/wvr-elements/src/lib/wvr-lib.module.ts
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.html
- projects/wvr-elements/src/public-api.ts
- src/index.html
Resolves TAMULib/tamu-library-components#221
> sprint13-221-handlebars

- .wvr-ud/static-assets/_styles.css
- .wvr-ud/static-assets/index-base.html
- .wvr-ud/static-assets/wud.js
- scripts/build-wvr-ud.js
Resolves #260 Weaver Usage Documentation should include the component template in tab list
> sprint13-260-template-tab-documentation

- projects/wvr-elements/src/lib/core/wvr-animation-component.ts
- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
> Fixed animation regression

- projects/wvr-elements/src/lib/core/animation.service.ts
- projects/wvr-elements/src/lib/core/template.service.ts
- projects/wvr-elements/src/lib/core/theme/theme.service.spec.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.spec.ts
- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
- projects/wvr-elements/src/lib/wvr-icon/wvr-icon.component.spec.ts
Added unit test for button properties
> sprint13-code-coverage-tests

- scripts/build-wvr-ud.js
…al static asset for usage doc script
> sprint14-236-usage-doc-script-options

- CHANGELOG.md
Updated Change Log file with features 1.8.0 release has
> change-log-updates

- projects/wvr-elements/src/lib/core/mobile.service.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.scss
Resolves Part of  https://github.com/TAMULib/tamu-library-components/issues/256
> sprint-15-header-in-tablet-layout

- projects/wvr-elements/src/lib/core/actions.ts
- projects/wvr-elements/src/lib/core/store.ts
- projects/wvr-elements/src/lib/core/wvr-core.module.ts
- projects/wvr-elements/src/lib/core/wysiwyg/wysiwyg.actions.ts
- projects/wvr-elements/src/lib/core/wysiwyg/wysiwyg.effects.ts
- projects/wvr-elements/src/lib/core/wysiwyg/wysiwyg.reducers.ts
- projects/wvr-elements/src/lib/core/wysiwyg/wysiwyg.ts
- projects/wvr-elements/src/lib/shared/wvr-shared.module.ts
- projects/wvr-elements/src/lib/wvr-wysiwyg/wvr-wysiwyg.component.html
- projects/wvr-elements/src/lib/wvr-wysiwyg/wvr-wysiwyg.component.spec.ts
- projects/wvr-elements/src/lib/wvr-wysiwyg/wvr-wysiwyg.component.ts
- src/index.html
> Sprint 15 322 wysiwyg state management

- .github/workflows/build.yml
- package.json
- projects/wvr-elements/src/lib/core/actions.ts
- projects/wvr-elements/src/lib/core/modal/modal.actions.ts
- projects/wvr-elements/src/lib/core/modal/modal.effects.ts
- projects/wvr-elements/src/lib/core/modal/modal.reducers.ts
- projects/wvr-elements/src/lib/core/modal/modal.service.ts
- projects/wvr-elements/src/lib/core/modal/modal.ts
- projects/wvr-elements/src/lib/core/store.ts
- projects/wvr-elements/src/lib/core/wvr-core.module.ts
- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
- projects/wvr-elements/src/lib/shared/wvr-shared.module.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.html
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.spec.ts
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.ts
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.html
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.scss
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.spec.ts
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.ts
- projects/wvr-elements/src/public-api.ts
- src/app/app.module.ts
- src/index.html
> Sprint15 319 button click event

- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.html
Modified wvre-button to wvr-button-component
> Modified wvre-button to wvr-button-component for tl-modal

- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.html
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.ts
- src/index.html
> Modal button is now toggle-able

- package.json
- projects/wvr-elements/package.json
- projects/wvr-elements/src/lib/core/wvr-core.module.ts
- projects/wvr-elements/src/lib/shared/styles/_variables.scss
- projects/wvr-elements/src/lib/shared/theme/default-dark-theme.json
- projects/wvr-elements/src/lib/shared/theme/default-theme.json
- projects/wvr-elements/src/lib/shared/theme/theme-variants.ts
- projects/wvr-elements/src/public-api.ts
> Added new theme variants

- scripts/build-wvr-components-static.js
> Wvr Wysiwyg is now available in usage documentation

- projects/wvr-elements/src/lib/core/theme/theme.reducers.spec.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
> Added provision to delay display of the dropdown menu on mouse hover

- CHANGELOG.md
- README.md
- package.json
- projects/wvr-elements/package.json
- projects/wvr-elements/src/lib/core/store.ts
- projects/wvr-elements/src/lib/core/theme/theme.reducers.spec.ts
- projects/wvr-elements/src/lib/core/wvr-core.module.ts
- projects/wvr-elements/src/lib/shared/styles/_variables.scss
- projects/wvr-elements/src/lib/shared/theme/default-dark-theme.json
- projects/wvr-elements/src/lib/shared/theme/default-theme.json
- projects/wvr-elements/src/lib/shared/theme/theme-variants.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.ts
- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.html
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.ts
- projects/wvr-elements/src/public-api.ts
- scripts/build-wvr-components-static.js
- src/index.html
- Weaver Modal button should be toggle-able. (#329 )
- WVRWYSIWYG is not appearing in the usage documentation. (#330 )
- WVR Theme Variants should be expanded to include all needed variant names. (#334)
- Weaver Component's Modal Component should utilize the wvr-button-component intead of the wvre-button. ( #341)
- Weaver component should provide additional theme variants. ( #342)
- Weaver drop down menu should have a delay on hover prior to displaying the dropdown menu. ( #344)
> Sprint17 staging

- projects/wvr-elements/src/lib/core/theme/theme.service.ts
- projects/wvr-elements/src/lib/shared/styles/_variables.scss
- projects/wvr-elements/src/lib/shared/wvr-themeable.component.ts
- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.ts
- src/_variables.scss.hbs
Resolves #347 Weaver components should offer a default theme group (modeled after btn)
> Weaver components should offer a default theme group (modeled after btn) #347

- .gitignore
- projects/wvr-elements/src/lib/shared/pipes/default.pipe.ts
- projects/wvr-elements/src/lib/shared/pipes/safe.pipe.ts
> [Issue 380] Refactor to pure pipes.

- projects/wvr-elements/src/lib/shared/wvr-base.component.ts
- projects/wvr-elements/src/lib/wvr-it-works/wvr-it-works.component.spec.ts
> [Issue 381] Remove isMobileAgent from base component.

- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.ts
- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.ud-examples.html
> [Issue 388] Afford input text color on text component.

- projects/wvr-elements/src/lib/core/manifest/manifest.effects.ts
- projects/wvr-elements/src/lib/core/rest/request-options.ts
Fixed null safety issue, and the template variable syntax.
> Added null safety and string interpolation to path vars

- projects/wvr-elements/src/lib/shared/utility/projection.utility.ts
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.ts
This provides a consistent approach for content projection within weaver components.
> [Issue 236] Content projection utility

- src/index.html
Resolves #348 The tabs component should support theming
> Issue #348 - The tabs component should support theming

- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.scss
relates TAMULib/tamu-library-components#389
> Issue 389: The mobile menu slide out tray continues to allow links to be clicked on when closed.

- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.scss
Classes are not used everywhere, but the template attribute is essentially a requirement.
Utilize the template attribute and use all of the known parts.
resolves #476
> [Issue 476] Collapsible Card is not completely collapsible.

- projects/wvr-elements/src/lib/core/wvr-core.module.ts
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.html
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.scss
Fixes issue for [ADA - Issue 3: Missing Skip navigation link #424](https://github.com/TAMULib/tamu-library-components/issues/424) 
A new ID will need to be created for the main content as `wvre-main`.
> Added skip to content button

- package.json
- projects/wvr-elements/src/lib/shared/styles/_variables.scss
- projects/wvr-elements/src/lib/wvr-alert/wvr-alert.component.scss
- projects/wvr-elements/src/lib/wvr-button/wvr-button.component.scss
- projects/wvr-elements/src/lib/wvr-card/wvr-card.component.scss
- projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.scss
- projects/wvr-elements/src/lib/wvr-footer/wvr-footer.component.scss
- projects/wvr-elements/src/lib/wvr-header/wvr-header.component.scss
- projects/wvr-elements/src/lib/wvr-icon/wvr-icon.component.scss
- projects/wvr-elements/src/lib/wvr-it-works/wvr-it-works.component.scss
- projects/wvr-elements/src/lib/wvr-list/wvr-list-item/wvr-list-item.component.scss
- projects/wvr-elements/src/lib/wvr-list/wvr-list.component.scss
- projects/wvr-elements/src/lib/wvr-modal/wvr-modal.component.scss
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-li/wvr-nav-li.component.scss
- projects/wvr-elements/src/lib/wvr-nav-list/wvr-nav-list.component.scss
- projects/wvr-elements/src/lib/wvr-tabs/wvr-tabs.component.scss
- projects/wvr-elements/src/lib/wvr-text/wvr-text.component.scss
- projects/wvr-elements/src/lib/wvr-wysiwyg/wvr-wysiwyg.component.scss
- scripts/serve-dist.js
- src/_variables.scss.hbs
- src/index.html
- remove redundant style variables in each component
- add description meta tag
- add compression to start dist
> Redundant variables
